// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARwbKY_nTiH73aTS0oHDQdHjGHDyTga6A',
    appId: '1:804312735358:web:674cde7feea47b57fb822f',
    messagingSenderId: '804312735358',
    projectId: 'bookbus-b4815',
    authDomain: 'bookbus-b4815.firebaseapp.com',
    storageBucket: 'bookbus-b4815.firebasestorage.app',
    measurementId: 'G-NPGPKJ03Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8_l1PUwvIX-yrEXbuuqInenEygyiLUNA',
    appId: '1:804312735358:android:4941dd48e4949fdafb822f',
    messagingSenderId: '804312735358',
    projectId: 'bookbus-b4815',
    storageBucket: 'bookbus-b4815.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Q1jXkJ2Jb5uju2RSnGesqZfdzi2ra_4',
    appId: '1:804312735358:ios:8e942b5e72bd4fc3fb822f',
    messagingSenderId: '804312735358',
    projectId: 'bookbus-b4815',
    storageBucket: 'bookbus-b4815.firebasestorage.app',
    iosBundleId: 'com.example.bookbus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Q1jXkJ2Jb5uju2RSnGesqZfdzi2ra_4',
    appId: '1:804312735358:ios:8e942b5e72bd4fc3fb822f',
    messagingSenderId: '804312735358',
    projectId: 'bookbus-b4815',
    storageBucket: 'bookbus-b4815.firebasestorage.app',
    iosBundleId: 'com.example.bookbus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARwbKY_nTiH73aTS0oHDQdHjGHDyTga6A',
    appId: '1:804312735358:web:78520b4a80114789fb822f',
    messagingSenderId: '804312735358',
    projectId: 'bookbus-b4815',
    authDomain: 'bookbus-b4815.firebaseapp.com',
    storageBucket: 'bookbus-b4815.firebasestorage.app',
    measurementId: 'G-Q68RDYVND2',
  );
}
